//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЗИ_лаба1
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int id { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public Nullable<int> blocked { get; set; }
        public Nullable<int> passLim { get; set; }
    }
}
